language: python
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install g++ openjdk-7-jdk python-dev python3-dev

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - python -m pytest tests